create table if not exists public.leaderboard_scores (
  id bigint generated by default as identity primary key,
  nickname varchar(16) not null,
  score integer not null check (score >= 0),
  created_at timestamptz not null default now()
);

create index if not exists leaderboard_scores_rank_idx
on public.leaderboard_scores (score desc, created_at asc);
